### ISSUE TITLE
To-Do-List

### ISSUE THREAD

**Issue by NinaWieland** [archer96/wg_planer#1]
- [ ] Add Icon
- [ ] Create new WG
- [ ] Add WG members
- [ ] Add introduction screen

**Comment by archer96** [comment]
Closed as we have moved to YouTrack.
